# Generated by Django 5.1.4 on 2025-01-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='Service',
        ),
    ]
