# Generated by Django 5.1.4 on 2025-01-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_services_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('contnum', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('timing', models.CharField(max_length=50)),
            ],
        ),
    ]
