# Generated by Django 5.1.4 on 2025-01-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(default='fas fa-cogs', max_length=100),
        ),
    ]
