# Generated by Django 5.1.4 on 2025-01-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
