# Generated by Django 5.1.4 on 2025-01-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='detail',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='icon_class',
            field=models.CharField(blank=True, default='fas fa-cogs', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='procom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='story',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
