# Generated by Django 5.1.4 on 2025-01-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_about_detail_alter_about_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corevalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=300)),
                ('icon_class', models.CharField(blank=True, default='fas fa-cogs', max_length=100, null=True)),
            ],
        ),
    ]
