# Generated by Django 5.1.4 on 2025-01-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_corevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=300)),
                ('proimg', models.ImageField(blank=True, null=True, upload_to='projectimg/')),
            ],
        ),
    ]
