# Generated by Django 5.1.4 on 2025-02-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_pricingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='story2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
